version: '3.5'

services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./src:/work/${COMPOSE_PROJECT_NAME}:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work/${COMPOSE_PROJECT_NAME}

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ./src:/work/${COMPOSE_PROJECT_NAME}:delegated
      - ./docker/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: /bin/sh -c "envsubst '$$COMPOSE_PROJECT_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  db:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-homestead}
      - MYSQL_USER=${DB_USERNAME:-homestead}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    ports:
      - ${DB_PORT:-3306}:3306
